modLoader="javafml"
loaderVersion="[33,)"
issueTrackerURL="https://github.com/MC-U-Team/GJEB-GammaJustExtremeBright/issues"
displayURL="https://u-team.info/mods/gjeb"
logoFile="logo.png"
credits="Team U-Team"
authors="HyCraftHD"

[[mods]]
	modId="gjeb"
	version="${file.jarVersion}"
	displayName="GJEB (GammaJustExtremeBright)"
	updateJSONURL="https://api.u-team.info/update/gjeb.json"
	description="This mod just let you customize your gamma ingame from 0% to 1000%."
	
	[[dependencies.gjeb]]
	    modId="forge"
	    mandatory=true
	    versionRange="[33.0.0,)"
	    ordering="NONE"
	    side="CLIENT"
	
	[[dependencies.gjeb]]
	    modId="minecraft"
	    mandatory=true
	    versionRange="[1.15.2]"
	    ordering="NONE"
	    side="CLIENT"